[workspace]
resolver = "3"
members = [ "avr-base", "keyboard_constants", "lufa-rs", "rust_keyboard"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
codegen-units = 1
