[workspace]
resolver = "3"
members = [ "avr-base", "keyboard_constants", "lufa-rs", "rust_keyboard", "qmk", "qmk_sys" ]
exclude = [ "keyboard_macros" ]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
codegen-units = 1
