[workspace]
resolver = "3"
members = [ "avr-base", "rust_keyboard", "qmk"]
exclude = [ "keyboard_macros", "eeprom_magic" ]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = "fat"
opt-level = "z"
codegen-units = 1
