[package]
name = "eeprom_magic"
version = "0.0.1"
edition = "2024"

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[build-dependencies]
# Optional, used to print linker hints
