[build]
target = "./atmega32u4.json"

[target.atmega32u4]
rustflags = [ "-C", "target-cpu=atmega32u4", "-Zlocation-detail=none", "-Zfmt-debug=none" ]

[unstable]
build-std = [ "core" ]

[env]
AVR_CPU_FREQUENCY_HZ="16000000"
