[build]
#target = "avr-none"
target = "./atmega32u4.json"

[target.atmega32u4]
rustflags = [ "-C", "target-feature=+crt-static", "-C", "target-cpu=atmega32u4", "-Zlocation-detail=none", "-Zfmt-debug=none" , "-C", "link-arg=-Teeprom_magic/eeprom.ld"]

[unstable]
build-std = [ "core" ]

[env]
AVR_CPU_FREQUENCY_HZ="16000000"
F_CPU="16000000"
ARCH="ARCH_AVR8"
BOARD="BOARD_USBKEY"
MMCU="atmega32u4"
LUFA_CONFIG_PATH = { value = "qmk", relative = true }
